---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: clickstack-mcp-credentials
  namespace: nexus
spec:
  encryptedData:
    api-key: AgARk84eeHhdJIONrlmJlrqTiQqPUwk9gBW5Sm4WC+7OIsiWVAB3FEJROfGpFQ0kH4WZzb3RQRLveRYsJhqNspuVifFoiy4dXCwxTdvlkJtDLw3NQWP4luWCnOTRcDhUAgkpBnzOj2lWIKchZDNP1aW4Go2g7OMvgJRoYnTCqGQldo62WAHmpci21R0aVc7+/np4dX19MqX5t7rEbIUIdK3PNPGYZ/kqUaRx9fMMu9l2SHveYWPxc1jgFzIKTX+DrctLtdSC1o+uBkhP1bPn9ww1AXcz3tclfQfGls/QDTHOPDUdQ6I7ZNr9bdJip/hwbORm1Z7Rn9Gay6epXoI7pSXNKlpjV+xiq9ukHm7L7JN3GF4y/zQVdUi2jVfSrG0XJs7ivX3j3ibfUJkwjvq1EvsdBBQeZajvBCDilfU4C2OVSKntLTfXkGCp0oK/XuFoefCEB6+A+W2FGGbssrOuMc3AWJhetf0Gn9o/BUYYD6fgy9x7/u+BVN+Du9ZgFv6rUL6KSbKFDYRLpueeTvL7kFId1oNl1Rd3xMQB8T3H2n24C12dhUKyBJijI0A0f+aSXeCdiD4HJLkEmBKBu7x4chtZQTVh0IF0dUESUszGNoSGmMjG0xQySrOjwRcEqgLUxX63rAzd4C0BjRg76SUqW08nl+uPO3UDXExmoF8SUspidDnKoCbgRCINdOc1osXNLzfhOE9MK+RXc5JmF89eto4zAPUYn3oExwE78/cOHg8681WrMOQ=
  template:
    metadata:
      name: clickstack-mcp-credentials
      namespace: nexus
