apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-mcp-credentials
  namespace: nexus
spec:
  encryptedData:
    GITHUB_PAT: AgA+k+hXiyRhz1BqcbUsrjsEuHTP9LjKz5i+MNAxNBP/ZuqHLDrF5n7hhOpVgry8jtM/Zo/rzfs2xW/pGKbRxyx5u7vAE/TTHbstYEtTO6J8ytYabvlFOm2C8zPwL1YmbQGzFInd9BtaeuqhB+84/1pu0xM32izf2vb/nwQYsNsR7u2wztxTI+p1CcCgdwPT3zaN7coGIGusjQrBZENMI69zVo87UsjrJZ6boDQMQgsLhV6wjeMvwTfJBF026NW3Fl06YLrlBimI9DFtLqDLpySe5TozgWzpTzeAKDf9goWxuuSBT3JXsgUHEY42StUafdjAdVhqa1d8e+g3i08ZYMOBnjxX79s4NWe8DARO1mSDL9tl3qKlV9tiglzokDGKW+s9X93dwLdf0hIy7rxlRECZ6NJc2kv5DTM4v1CVZhSCmzJ2Rz6Ddxf/aZlYPndPmc53Y29+f8M5gr/AsvVTwe09V8I9ofAAFnlNFDlruCLQnKQ58Y2FCB7cP+PwF6CajqhP9dzEIjGusD8zCHh8xUoNLW/7GiutBXHry3KOc2KeUS1iiSRBlQIYTxHeMo78ht3iFFR3rJ15+2+cw0VyWI5XVhaenTfFNl+JNUNaa9LepdZJ8GnWH0QqRDGyj0vHlcolreSoGv7bqHtomDVF4psrXKLjB99TvBICOY0qv1lwW02xt6l5GK8w5V+U453IjeZGHIhxDdQ6j1g0kOBqDAtEra6tZruZGjgKjv9a1ukruUXVYytWbTKrZRPgI8XpQOwYC/8doz5Ue9CLKWLnnnBrUVSLUsawGBqlIcOc7X4OD9mWwpNSNdPqG+/cEk4=
  template:
    metadata:
      name: github-mcp-credentials
      namespace: nexus
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nexus-lific-credentials
  namespace: nexus
spec:
  encryptedData:
    LIFIC_API_KEY: AgClHOwpyI2vSj1M5XMSqo0EkrE1PAjqEihlFhOBH9Le4iMaRpJcKpPGnR/rd9oDPExVAaXboPww9AkM5N82Hau0e+31cWYMqFNjQ0vh7p6hGTQdpqMuR2jainqD8LcKRlLt05k4bHCi9UHfpHgN5GpFMN+kovQzZK4mnzjcEjPmAp9gQIkkcGinDtaAwe9INv4iJkJzT8y8GffHzCMKKzJZNV+skaoEypvgeFRswG2433Qh9Kcnes6bg0lKkG1bL75Qs6umVA/2BUgqO9eRZEuHBRSUoHW+R82CZ+XJwIsXudhxvTHjePwiKc4KMn4J0TbjRrYH81n2Q0i4S0/Z+5y4qZw8JLm0/746rl7twngYDbvzQafpuVbW5TacXGdHyCuQWys0clT/taGGqXseDGixfhxzlT6n9N47nq+g22cj7vFndGm81f11scIyKWN+ZJBQTV4J2Adh7BY8YubM4MzziFjSRCS31B76I+SJUNx3972xXcM0AbxG0OWkauEUARUX0dne1fObezo0GTT78MLLEihfRkcrw4xqR9psX/DMcNiE37Qt0FgbC4UjZ1U9X7rCwX/q4fhgQxV6t1D9FU8YElQwlCZMGKZri9VNVCT6LT3+Xxr5J7ZbaeKvp9BDvpr4/gu3w1PIcDIlSeAtWzhupMMk4QcZU1zOGtctN1OYb0J/u7SMIrVn4MnNyinCrewvzIIqD8BgPqcD/4prI/QF7GzVA4LN1Z4cVwH2XjvFLu6pY3+71j7jbagS56DX3dlf5T4ery+BCiHtNENNY/pLXPkO
  template:
    metadata:
      name: nexus-lific-credentials
      namespace: nexus
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nexus-tunnel-credentials
  namespace: nexus
spec:
  encryptedData:
    CONTROL_PLANE_API_KEY: AgCYOdGY7dPSI5bDNWlX6xbgA2ZenqrY5Csz6GEPi82xktz0voVorBCtloGRWwuDyK+/MPtPfQ12w4HnGOlHfCGzios9k0TExd5t0yZwmV7DoYX9LCjqniv8U8jUh7jfDK7daY+YgVdPoGrMMEozdXchdwvdDjXoCCc2Z0YJGPAt8vespEYhcI2TLqu3uXUpOcgmLXajuAoajHdREGnqzvnp9I+4IKnPvefiyBpk4bIEy6i9waIpf3X6bRzS9GNGe5BTH0X2aByTDp8TigHHmpjysz+YD4H8fI19wxgKNa0kXNgTeRwLaiIDqfxMx41LuV58psVtB7noraWQec6KlNDLk9xgY5cbr6akPQWmagKPORN0cBuCOuj6DrVMGo9M1N0n0KZkC9toF4QH09Xyrwhphv5hVtmvnBWrf1JyXr4B9P5t1bbA2wzuyh9GMYVzc7W39a10GMStmSIfReCy/HGGHE98hkOHpAdmoTycYH2CN1jVX25zRhBji8eGsG1YTOgcyFB0y4faWDkRO0AhY1rUnMWXA4V0dgK1/1TVvyM5xCi71DV/Udh/HA1eucuGPxE68dlSXUlq+kyBIgbf8ydlDu3Qc8nssJLmbRFtTCFzY8E0vx31PHSii3G4ETgJRrxb6tekHJWYmGQ7J/fB4N3oBldOvKcuBuHisCFqU0kOpj7U+TZ/ZSmXFtEur+9DTx3WBo20Ncdy35hvEm6ZAZa0ALtB2mMPRCRN+svEr6jDUr/Z2chesvb8eQxQULT0Q4XqXdpLECHbPPkDefiTtL0lBrziRDsrwPcQQqLc3GdyLMXccKptlQHSyyVXmA9F6cJzqjzQe96UjxTtYasHSPFDf2dxmDX3QEwX/RRqmEEezlUDz0617679zd4TgkZOV1H2iigqdL7frNRAfBN/m25VZRgLtQ==
    CONTROL_PLANE_TUNNEL_ID: AgCSEwxh62XJJt9Sa1zDFFejEnlE/Qwv+Xt2oRK2rsnHj0rLZYgOnW9s74+8NL5AXa89117M4krQivJxIy9fJr2S2WTW8Z76azg0pbkXXsSkcVbVKP/X2H4fBhwbx4Lwc3EYLHcwCuSph82AapdyjntZFNJqmvCyp/iUwKHRceJDH2DmVR+38AsiVLPGLGvu/9TkJlMVtY9/n6C36ryyRSghq4Gqk/U3AVsiK1YfCJKdp8bdbwUhpONQxj0nrFwFgceftjcorKU3HzmJXmBBbxcaIBRym+IZ0kN7yrMYcj/Tpiz9KFsBOpSWxGffF5GJC/3MzNlRo6jGplVmEBrI7PBbeQN1ieCBnsxvq4cfSBgGAY2APPinGWSKDyQbUDhwzInkd19tBnryfi0122N8p51iO7w13m7T5vfn2qX3IggJZXOtwQxGAGq8OEk980bCpbaiOWjnsCYzzyURrDcwLb1yv46amNS/oM7dEAl0os15iCGuvDMVyeEBk5wFmLfLIGlXUqvpdtxHoMIpcM6mhfw43sAgmf/p1Si0TeqpTpXnpagbgBVltU4VadAnZaSTFCi4vkG/4WSazPyZUJtMVJEC97LAM9a6zuodAe/QxAPXinO1zTrprZz5Gj/l/PwF1cRRB2SCigx4xltAV8K+IAHDOB8iewGRZ699rKm85Za2JkMUsSA3cgv1p7KYRZsevSTXD91WiS45iDsObu/i+a2Vd0Y3/23UVySFPLtsLT5PVLRZUCqIvf0=
  template:
    metadata:
      name: nexus-tunnel-credentials
      namespace: nexus
    type: Opaque
