apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: anvil

resources:
  - github.com/blogle/anvil//k8s/base?ref=e5d053f368026ce5c612bcff52d43b326e1e1ebf
  - certificate.yaml
  - ingress.yaml
  - github-app-credentials-anvil.sealed.yaml

images:
  - name: ghcr.io/blogle/anvil
    newTag: sha-e5d053f368026ce5c612bcff52d43b326e1e1ebf
  - name: ghcr.io/blogle/anvil-sandbox
    newTag: sha-e5d053f368026ce5c612bcff52d43b326e1e1ebf

patches:
  - path: runtime-config.patch.yaml
  - path: profile-pvc.patch.yaml
  - path: profile-deployment.patch.yaml
