apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: anvil

resources:
  - github.com/blogle/anvil//k8s/base?ref=b4261a6988b4363191b7b28c7089299f08832a7d
  - certificate.yaml
  - ingress.yaml
  - github-app-credentials-anvil.sealed.yaml
  - nix-shared-pvc.yaml

images:
  - name: ghcr.io/blogle/anvil
    newTag: sha-b4261a6988b4363191b7b28c7089299f08832a7d
  - name: ghcr.io/blogle/anvil-sandbox
    newTag: sha-b4261a6988b4363191b7b28c7089299f08832a7d

patches:
  - path: runtime-config.patch.yaml
  - path: profile-pvc.patch.yaml
  - path: profile-deployment.patch.yaml
  - path: nix-daemon.patch.yaml
  - path: anvild-rollout.patch.yaml
