apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: anvil

resources:
  - github.com/blogle/anvil//k8s/base?ref=277d83b10c01e7464cb14331d995ba3c568be23f
  - certificate.yaml
  - ingress.yaml
  - github-app-credentials-anvil.sealed.yaml
  - nix-shared-pvc.yaml

images:
  - name: ghcr.io/blogle/anvil
    newTag: sha-277d83b10c01e7464cb14331d995ba3c568be23f
  - name: ghcr.io/blogle/anvil-sandbox
    newTag: sha-277d83b10c01e7464cb14331d995ba3c568be23f
  - name: ghcr.io/blogle/anvil-nix-daemon
    newTag: "sha-d750064c2f96d64e7d3ffc271631a710b1ad6167"

patches:
  - path: runtime-config.patch.yaml
  - path: profile-pvc.patch.yaml
  - path: profile-deployment.patch.yaml
  - path: nix-daemon.patch.yaml
  - path: anvild-rollout.patch.yaml
