apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anvil-nix-shared
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-zfspv-shared-ext4
  resources:
    requests:
      storage: 100Gi
