apiVersion: batch/v1
kind: CronJob
metadata:
  name: anvil-nix-gc
spec:
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: nix
              persistentVolumeClaim:
                claimName: anvil-nix-shared
