apiVersion: v1
kind: ConfigMap
metadata:
  name: anvil-runtime
data:
  ANVIL_PREVIEW_DOMAIN: preview.thejeffer.net
  ANVIL_ANNOTATION_PREFIX: anvil.thejeffer.net
  ANVIL_SANDBOX_IMAGE: ghcr.io/blogle/anvil-sandbox:sha-7452504051c35afef9a4a65df708ce1b15ba38ca
  BASE_DOMAIN: preview.thejeffer.net
  AGENT_SANDBOX_ROUTER_URL: http://sandbox-router-svc.agent-sandbox-system.svc.cluster.local:8080
