apiVersion: v1
kind: ConfigMap
metadata:
  name: anvil-runtime
data:
  ANVIL_PREVIEW_DOMAIN: preview.thejeffer.net
  ANVIL_ANNOTATION_PREFIX: anvil.thejeffer.net
  ANVIL_SANDBOX_IMAGE: ghcr.io/blogle/anvil-sandbox:sha-e545b1cd3bce00706d767a86d68693ca5f1d5d40
  BASE_DOMAIN: preview.thejeffer.net
  AGENT_SANDBOX_ROUTER_URL: http://sandbox-router-svc.agent-sandbox-system.svc.cluster.local:8080
