apiVersion: v1
kind: ConfigMap
metadata:
  name: anvil-runtime
data:
  ANVIL_PREVIEW_DOMAIN: preview.thejeffer.net
  ANVIL_ANNOTATION_PREFIX: anvil.thejeffer.net
  ANVIL_SANDBOX_IMAGE: ghcr.io/blogle/anvil-sandbox:sha-8d84110f3ae431d92e004d7dbd2cb9befb7fe6e1
  BASE_DOMAIN: preview.thejeffer.net
  AGENT_SANDBOX_ROUTER_URL: http://sandbox-router-svc.agent-sandbox-system.svc.cluster.local:8080
