---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: clickstack-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgBWT5h420lAUYALDzv3uT+F716w2IHRe/nZZbnY+Evni93q88Hh0p8qa1awh97FI6paLPMqF2WrU/FrX+tVO767y+gqODrVLEw2GgXfIeZHg/1FaCVE79Y0ijpqnlAHC0IRbkZqNkRG8A1zSPrDWpm6qeKj6FFXg8jHz8rzBMi/WMg24rERZLXtu2wLBDc9w1ZiOizlBph1w00Mvwj2dOANv4FC32T62Vk/9NqFwVWPx/L1BpvJMcdomaCpUkiBTZe6TdLc5Y1nPGi6ss/aFg/IZJVcxE4dZgchMSIxcuVqATnaYZVfqoy2HF3NjYLluVteviJJJKXxhX1okncXkOeVbhhZC4QkyPNp3hYjHKDEZGNry5HkBVtbP9vMPwgG0M3+s1lSJOW9E/T+TW6F1gMIG00hcey4X/AhQ6fXvPzDzsEbHrTxloGTQ9Byv7tek6c7Q1azhR5i5AZ7l3wk/H10fSVT4bM7w6yblFFHxqBnHOQQRgrJB2uUcY9K8tfjOgoIZcuW4wogyTXedJMrnGERbi4QQJ95tTM3R6huD30XdlCq8/0oabV+bjLtQO19yYikJVP9Rl2fUu+yglzj2amm66pgK3yjGR4S9ncOrUYe2sIPyWAtQFeOs6NAzzjc3CR7uENOSnaThs2G+2WIFcvPu13pUyBZGi6KPQEFNi7j4ePveE92Nao+eAM3tpKBevDq2Xg0R1JS7HgCcR7ayx9gH7FXroOdsjG8uxrJi+Cmw7cE1DpdvCAwUruLDXk47yxfVttlUOXMBvJa2tbV7wXFw7Zh/aYQmBGCpnLIoS96opNBGYQD8HSVfdL4ZB6lDMPXadoPYoCknwVuOb2k7X20/6OSpjc6L2f5gDpPQHwoFnn8iiLKllmSyIQGrb+PeBt9tkBBWOcF6bNycN5SwFrnhyNSiApw+e39T0sI9GXCo1gJjlilwoxqIU6OY1k8U/WzkfptZcE5pfoQ2l384j6jJvI9lW8YceGinaVdsuxhfRb+mo0Q3zBmD1KjdatWxTVcGOn9lHrNKf/pUeIEkSsAJtBnBFnkZc9dRwAhTgOlKcVetS/4a1aFByyS+znssxYJmeZ3Lz/3ggQNvCCxqpnB4UXGhmUqbRz3M5IFGCas4tQxJAxtsJ7lBcfdMb6kCSiJWgUYhdfP6DahQWRLOBSls6M6vyo=
  template:
    metadata:
      name: clickstack-values
      namespace: kube-system
