apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-zfs
  namespace: observability
spec:
  storageClassName: openebs-zfspv-retain
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-zfs
  namespace: observability
spec:
  storageClassName: openebs-zfspv-retain
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-zfs
  namespace: observability
spec:
  storageClassName: openebs-zfspv-retain
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-zfs-prometheus-kube-prometheus-stack-prometheus-0
  namespace: observability
spec:
  storageClassName: openebs-zfspv-retain
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-zfs-alertmanager-kube-prometheus-stack-alertmanager-0
  namespace: observability
spec:
  storageClassName: openebs-zfspv-retain
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
