apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sandbox-server-state-zfs
  namespace: openhands
spec:
  storageClassName: openebs-zfspv-retain
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
