apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dojo-prod

resources:
- github.com/blogle/dojo2//deploy/k8s/base?ref=master
- namespace.yaml

images:
- name: ghcr.io/blogle/dojo
  newTag: v0.1.0
