apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager                    # must match the Config below
  namespace: kube-system                # helm-controller lives here
spec:
  repo: https://charts.jetstack.io
  chart: cert-manager
  version: v1.18.2                      # latest stable as of Jul‑2025
  targetNamespace: cert-manager
  set:
    installCRDs: "true"                 # install CRDs with the release
---

apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  valuesContent: |-
    extraArgs:
      - --dns01-recursive-nameservers-only
      - --dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53
---

apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: oglebrandon@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - dns01:
          cloudflare:
            email: oglebrandon@gmail.com
            apiKeySecretRef:
              name: cloudflare
              key: api-key
        selector: {}   # match all Certificate / Ingress requests
