apiVersion: v1
kind: Namespace
metadata:
    name: external-dns
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: external-dns
  namespace: kube-system
spec:
  repo: https://kubernetes-sigs.github.io/external-dns/
  chart: external-dns
  version: 1.14.4
  targetNamespace: external-dns
  valuesContent: |
    provider:
      name: cloudflare
    policy: sync
    env:
      - name: CF_API_EMAIL
        value: oglebrandon@gmail.com
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            name: cloudflare
            key: api-key
