apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfspv
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: zfs.csi.openebs.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  # This dataset is created declaratively by NixOS and is not under k3s's
  # /var/lib/rancher tree. The driver creates one child dataset per PVC.
  poolname: rpool/safe/kubernetes
  fstype: zfs
  recordsize: 128k
  compression: lz4
  dedup: off
  atime: off
  logbias: throughput
  thinprovision: "yes"
  quotatype: refquota
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfspv-retain
provisioner: zfs.csi.openebs.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  poolname: rpool/safe/kubernetes
  fstype: zfs
  recordsize: 128k
  compression: lz4
  dedup: off
  atime: off
  logbias: throughput
  thinprovision: "yes"
  quotatype: refquota
