#!/usr/bin/env bash
set -e

project=mystic-advice-238223
bucket=ogle-vm-images

tag=$(date -u +%Y-%m-%d-%H%M)
name="cacheflow-${tag}"

echo "Building image: ${name}"
nix build .#cacheflow-gce-image
image=./result/*.tar.gz

# Copy the image to gcs
echo "Uploading image: ${name}"
gsutil cp $image gs://ogle-vm-images/$name.tar.gz

# Create compute image
echo "Creating vm image: ${name}"
gcloud compute images create $name \
  --project=$project \
  --source-uri=https://storage.googleapis.com/$bucket/$name.tar.gz \
  --storage-location=us

