apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: addrspace-apps
  namespace: flux-system
spec:
  interval: 1m
  path: ./addrspace/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: addrspace-platform
  timeout: 15m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: anvil-nix-daemon
      namespace: anvil
    - apiVersion: apps/v1
      kind: Deployment
      name: anvild
      namespace: anvil
    - apiVersion: apps/v1
      kind: Deployment
      name: anvil-router
      namespace: anvil
    - apiVersion: apps/v1
      kind: Deployment
      name: anvil-mcp
      namespace: anvil
    - apiVersion: apps/v1
      kind: Deployment
      name: anvil-profile
      namespace: anvil
