apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pocket-id-secrets
  namespace: auth
spec:
  encryptedData:
    encryption-key: AgB8IRKfPeCsqnjfYGRKTBgDDPSDqvXs364GflKxK3g90TvoOrmoDFwIHo3Dn+9waiCNa3iYJ14P6IGLKjMexRfG0p7wLJI3NQu1TSEQ7xtkYSV9RoYsKoqevSGvRYb6uTJiLQtZYKwU42XpSWPJUGLvyBmD2YIz1vpb9R+eDKoBQ7T4XbYXzq2s9rsYpftv3NHphvDm4vI/MKuyouwIJY14MVJfeDWpYWZjA2At9mSguOyyUOWjH5kcQZPC0bU2OuDkA++WUNBlM4vCBcbmU42UCW5CImMdWZki+BIUFPqfYdTN+oD3n6jQS49fgOesI3jFqMdvbpa/JuVVobqvcxNcDoudGrYhmGIw3bL7CniPFGVk9GvCkPPEy4mB7kiLZCasmUXZxEkwWfKcxoEnVbeD47zVHb/vUF25nK2d+kbDCjy+FBDDKuiJmhb5uWx+5wn2LFGq4ArB+oLdKkoBUh6WRu1LaohmqHYC8YQs6O97pYITvSBk2LGmzAEyUkP/G6PlpQK4ad/azEPdIEovEe2x0gwGCrvaAMqNSKjtO9fkd/YkFi6cK5/Mxi7j6KZWmxed+d3l3KkbI5Q1TsCzK+rsFjesUqez4lGlKu/5gKtrss2eFj/ex+esG9kLvuC2Lybjz5i2xthX2JoILkf/YUMdQJHqn7yFe1EwK7U7W7EPWTOcL3NmgA6Rx2ljJQuJ4qnVUJb3jX4TypYO1OyVZnywojREgKNm3k8uwOFfr+ggHfqF0IIMH8sMAP0PAQ==
  template:
    metadata:
      name: pocket-id-secrets
      namespace: auth
