---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tinyauth-credentials
  namespace: auth
spec:
  encryptedData:
    client-id: AgBfvakRMb6Qd7Wc6j5cYb+p6pNdBaTmUqx8hyLn17gf/1tW7vBvE5BcVz7tc6dlcCQq4HgMS3FAwVMj93H/BeR3pMyqPln142PTFCplbl/TZHheutRqXvFAtl9YhtlsbsmH0zzl8oa4lXKInsVk+TR6HB1j3GfkThoqz3vkQV20YA+wSxWLWYYZVBLUZcXNup9PtAI+FlPAqxBV3pH6/vpegqS8iwl+NIiPxN6cTgHsMW7FqdZsqClzLeRtcdrPeMEr5ydS8i9MM8VMOLO7MYB8U13YOn+Hj/N7AQuEMim+cy9hC4Z7lGCjPW328CFiGyySN4QqFYD/W7NsmSCTTAxB89ARLaNWqwSrdZfhM8UPD/+IICFRNqvFT7XGG/3j49tyQkWyc7/JcUbl+lEu9MCafbF3qHAYFDN23G7NTawVF08WAZYK9kUdW+syu+TxRGASYX84OYDw8EN9nwZKk5lSPANHCHogafDt5btmFXBAqUyhaEwiHotCvF81qwqD1zAftDSYRJQJLdDelQSi4cOhLG2aaPyCyQz/3Bik1fG7cZh+spEdFdyqyM3FUc9YIO3G2rEI1UWg5BSlpws/P/aKW8dz5O8qGjxefhTNcyGPKVK99Q94HosUUvM+xJZ8HjE0d8RTqHnpOXwYQ9/NV6BWbqEE7m1YbZeAjcXTnvlVcPKKynRlqcWx2LZ5eNyTwIc9MS0xMZxwYeClA/aQO/eS/3/JCsz6f6zjb6w/LJy+sioh7Ro=
    client-secret: AgBzpKPwSGsrPH2LFFem1Ri+hcx7UlzNOMoKjOGucQ5pTB/ygVzlZk22s2Llrt6o5JQyNNNTrwT2t9fuNBBi+YQAwi+1lioISWbiJPrfLvZsMvN4QaOenqfuqJxWCChDFfLPf8tEKtd6mK1XUxaGLd3kz7XCHZbSwYAqKHgh5K5OGUdw7Iabm44+ETkYBbxeq9MqYtPpUyT5J3QmhguSgjUmbkioTtNPRJ9hi33AsfUuZl7bQIgLLDBpRZE0EPUUr2EV7M2bYsb/8vAtQ6F+8KaqIMHfj1tX2+LfYS53iQwJucwNxk3e7W1heqKS2bSnIws/Pww2RiTeCY6Es8jSLBZscOKOBT8684d8pdbjM8tDpLMq91cX6APmF3UGzaI5uaiE+Da8Xg+yrJZV1e2Z5AwhfsuBtiwcHNqTP91ecMkP+cE+4GqYGw0ZCc78BJW286mBXmVPtfopT/bPNV7lNH2p5gc8KN60HyUSaXeD4mdMVzJ4wses9+yhnwuuJf40b/VcRAoqnDTcriVGUn1QXN0f/p06qfVnLt0N8f4Gdtu+nNRf/nBRoetFTrYd49pI9sX2FX0gLUjMxUwHQklqmxY7DarL/JJxFtYcEc5BeQcEYvr24z/m353bOeuYRr4ioZWdQ4Snc+RY0/TpKVr9zjtiR1h2biwg2MwnG8s4SzMFNbTw84h679a/yfywJTV1C34lMd3+WbBWc0dhBzdmWIr8jlOmgkmz0qN1wwiOfoIUeg==
  template:
    metadata:
      name: tinyauth-credentials
      namespace: auth
