---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jellyfin-sso-oidc
  namespace: media
spec:
  encryptedData:
    client-id: AgBb83M1mzE39aZNdZ2q1SbT4JULLqBuFx6VyvKn1ZeSl7q4EGDhNyU2d96IQR6YYrRoHuylSN+sFRm5tawd0q9fqbsZDjxVTK3RHSHVpv4J2VJ+Ph+wyvE7VUNMH6MoMNJqor83Bdc3iSDOHnUpDvQQ4gWstNR58Nfw1Gqu2nlG1jp7zDo9x7Q5A7HVKdXcAHpK+gHzSdeqvs5W4utl6DFJOqpILsbvadZ+Zung15aGN27OW2a6PeSEbfBN1nJZck/DbgcFSB4H5EV0JQoSURN8aC7EeP5c7rngH7vaQOIQyIM9DU7Ifq7Rg0tauodgLFIC/LMqc7MhTYXXiLX+inyFhXuuS+2lOZCf3iSbHV1Z9+MTIZaQgXT6ZcWT1U6MYEM1160woitIVtAAiYq9KaudfVNe/iozb848FXaYF6hSlcIfUXIvrjmsAtzWUi278Tk7TSt8qXqENv3LuG0nPU+/lGFUUv86y6cltXESlCblGOyy/lt+NjbmQqX42/mbg0pEFNZxQ1XQ3a3EXA68EKNXtp1wQbak6I7JeTQMFHftze/pT2Ec36RsKbR6hYdujWOVyTOGuudlsfBgkixPZsoYVOxytlhGE4FsF2pAVfXLrJ2XrMqE/tdYvbiASL7mg7K8J7tnabhD4p+IL6dQA2XkqMuxjbUWMPR+iWGSrdXLbQsj8AnpdEeHBk+FVtMsxRolsIH2iSIp2FwImBBFU2y1mHlpzuWom8IsU4KTztCT7cGUA1I=
    client-secret: AgArU3cU+0unL7m5Kc2DddALFzMLMbAbvwTwkDySZH8hvRfI0oWy8K5J3jHoWkKWjpQu8bOLNuOLLAA+P+HAxLllreSS327M49u+FMq54V6dKfjSECYwCKqdZQ/te7jOveMm2tFHGqeARg+TNnJeee9pev1ywLhvUfaYmiPHzUYr7l+QWbN35t7c7cZzvSAsKX7RDPuFYmaF678+iXGPQsHulrzrv0UObhUuXJ2lu88enMSZ1xKVtVGMuy7q8mECfuU492FSmvbAYM8RIuEOBpXih0aXIodTGc5rYWlJFY/32VOFTBREEH0nDIlXcuULB12tlRFpywC8M97r4nkDLC2wPVCjmJIVQTcv8pxLrenvnD0hd6V1Z0iOMG17s3kUoRJyW24TaxeLwAe1nh1auwrfVoBHUV7jU1v4/eWJ7PmWA2m3eiARz5LYca3XODwO263sbZwndqMvM0H2IRKuKrkL5FVSYYNGiPUcOrIdRvBzMPsDRnl+ADubDG4rz90XeKbRZVCUu/n9WmB4e7fkpt5F2mC/hDKCxwIyW7CEE9caeuGyWI6i6/c6iWbMXFdywX4UFuTqwiLWn93RdvhOFUYs4APr5/kSqL3JqXjvXultu+yLvY9JwsXdN6B0DmwJ90JvLmdGyZsRwBresPsd227QMuz0iBorvBHCIcT0Dofy11ELPyzSzr4I/kZWGISbI88u8n2ySdch0XHAxEzdiE482jH059LgNk5Qzyj34SIQvg==
  template:
    metadata:
      name: jellyfin-sso-oidc
      namespace: media
