resources:
  - media-namespace.yaml
  - media-volumes.yaml
  - flaresolverr.yaml
  - jellyfin.yaml
  - seerr.yaml
  - seerr-redirect.yaml
  - prowlarr.yaml
  - radarr.yaml
  - sonarr.yaml
  - transmission.yaml
  - dispatcharr.yaml
  - teamarr.yaml
  - acestream.yaml
  - m3u-playlists.yaml
