networks:

  ingress:
    driver: macvlan
    driver_opts:
      parent: eno1
    ipam:
      config:
        - subnet: "10.0.0.1/24"
          ip_range: "10.0.0.100/30"
          gateway: "10.0.0.1"

  internal:

volumes:
  acme:

services:

  traefik:
    image: traefik:v3.2
    command:
      # Tell Traefik to discover containers using the Docker API
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      # Enable the Trafik dashboard
      - --api.dashboard=true
      # Set up LetsEncrypt
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.email=${LE_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/certs/acme.json
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      # Set up an insecure listener that redirects all traffic to TLS
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      # Set up the TLS configuration for our websecure listener
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt
      - --entrypoints.websecure.http.tls.domains[0].main=${DOMAIN}
      - --entrypoints.websecure.http.tls.domains[0].sans=${SANS_DOMAIN}

    restart: unless-stopped
    env_file:
      - .env

    networks:
      internal:
      ingress:
        ipv4_address: 10.0.0.101

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/traefik/certs

    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik.rule=Host(`traefik.thejeffer.net`)'
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

      # Basic auth
      #- 'traefik.http.routers.traefik.middlewares=thejeffernet-auth'
      #- 'traefik.http.middlewares.thejeffernet-auth.basicauth.users=ogle:$$apr1$$5phWqjTo$$SrtzKVHTHasSCYrLzLJQ//'
