resources:
  - cloudflare-cert-manager.sealed.yaml
  - cloudflare-external-dns.sealed.yaml
  - cluster-issuer.yaml
  - metallb
  - traefik.yaml
  - zfs-storageclass.yaml
  - zfs-snapshotclass.yaml
  - storage-claims.yaml
