---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitmagnet-config-pv
  labels: { app: bitmagnet, component: config }
spec:
  capacity: { storage: 1Gi }
  accessModes: [ "ReadWriteOnce" ]
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [ "nandstorm" ]
  hostPath:
    path: /persist/bitmagnet/config
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitmagnet-config-pvc
  namespace: bitmagnet
spec:
  storageClassName: ""
  volumeName: bitmagnet-config-pv
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests: { storage: 1Gi }
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitmagnet-postgres-pv
  labels: { app: bitmagnet, component: postgres }
spec:
  capacity: { storage: 100Gi }
  accessModes: [ "ReadWriteOnce" ]
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: [ "nandstorm" ]
  hostPath:
    path: /persist/bitmagnet/postgres
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitmagnet-postgres-pvc
  namespace: bitmagnet
spec:
  storageClassName: ""
  volumeName: bitmagnet-postgres-pv
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests: { storage: 100Gi }

