---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-mcp-credentials
  namespace: nexus
spec:
  encryptedData:
    GITHUB_PAT: AgA+k+hXiyRhz1BqcbUsrjsEuHTP9LjKz5i+MNAxNBP/ZuqHLDrF5n7hhOpVgry8jtM/Zo/rzfs2xW/pGKbRxyx5u7vAE/TTHbstYEtTO6J8ytYabvlFOm2C8zPwL1YmbQGzFInd9BtaeuqhB+84/1pu0xM32izf2vb/nwQYsNsR7u2wztxTI+p1CcCgdwPT3zaN7coGIGusjQrBZENMI69zVo87UsjrJZ6boDQMQgsLhV6wjeMvwTfJBF026NW3Fl06YLrlBimI9DFtLqDLpySe5TozgWzpTzeAKDf9goWxuuSBT3JXsgUHEY42StUafdjAdVhqa1d8e+g3i08ZYMOBnjxX79s4NWe8DARO1mSDL9tl3qKlV9tiglzokDGKW+s9X93dwLdf0hIy7rxlRECZ6NJc2kv5DTM4v1CVZhSCmzJ2Rz6Ddxf/aZlYPndPmc53Y29+f8M5gr/AsvVTwe09V8I9ofAAFnlNFDlruCLQnKQ58Y2FCB7cP+PwF6CajqhP9dzEIjGusD8zCHh8xUoNLW/7GiutBXHry3KOc2KeUS1iiSRBlQIYTxHeMo78ht3iFFR3rJ15+2+cw0VyWI5XVhaenTfFNl+JNUNaa9LepdZJ8GnWH0QqRDGyj0vHlcolreSoGv7bqHtomDVF4psrXKLjB99TvBICOY0qv1lwW02xt6l5GK8w5V+U453IjeZGHIhxDdQ6j1g0kOBqDAtEra6tZruZGjgKjv9a1ukruUXVYytWbTKrZRPgI8XpQOwYC/8doz5Ue9CLKWLnnnBrUVSLUsawGBqlIcOc7X4OD9mWwpNSNdPqG+/cEk4=
  template:
    metadata:
      name: github-mcp-credentials
      namespace: nexus
    type: Opaque
