---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nexus-lific-credentials
  namespace: nexus
spec:
  encryptedData:
    LIFIC_API_KEY: AgClHOwpyI2vSj1M5XMSqo0EkrE1PAjqEihlFhOBH9Le4iMaRpJcKpPGnR/rd9oDPExVAaXboPww9AkM5N82Hau0e+31cWYMqFNjQ0vh7p6hGTQdpqMuR2jainqD8LcKRlLt05k4bHCi9UHfpHgN5GpFMN+kovQzZK4mnzjcEjPmAp9gQIkkcGinDtaAwe9INv4iJkJzT8y8GffHzCMKKzJZNV+skaoEypvgeFRswG2433Qh9Kcnes6bg0lKkG1bL75Qs6umVA/2BUgqO9eRZEuHBRSUoHW+R82CZ+XJwIsXudhxvTHjePwiKc4KMn4J0TbjRrYH81n2Q0i4S0/Z+5y4qZw8JLm0/746rl7twngYDbvzQafpuVbW5TacXGdHyCuQWys0clT/taGGqXseDGixfhxzlT6n9N47nq+g22cj7vFndGm81f11scIyKWN+ZJBQTV4J2Adh7BY8YubM4MzziFjSRCS31B76I+SJUNx3972xXcM0AbxG0OWkauEUARUX0dne1fObezo0GTT78MLLEihfRkcrw4xqR9psX/DMcNiE37Qt0FgbC4UjZ1U9X7rCwX/q4fhgQxV6t1D9FU8YElQwlCZMGKZri9VNVCT6LT3+Xxr5J7ZbaeKvp9BDvpr4/gu3w1PIcDIlSeAtWzhupMMk4QcZU1zOGtctN1OYb0J/u7SMIrVn4MnNyinCrewvzIIqD8BgPqcD/4prI/QF7GzVA4LN1Z4cVwH2XjvFLu6pY3+71j7jbagS56DX3dlf5T4ery+BCiHtNENNY/pLXPkO
  template:
    metadata:
      name: nexus-lific-credentials
      namespace: nexus
