---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: adapter-internal-token
  namespace: opencode-system
spec:
  encryptedData:
    token: AgA+zLSCPxpqlCLR65iv8kXpVyhA0jF1GeZyoaF1B+wCT9kC+JdiVQFi+df/Yi3hiaeVNRxH0DBTF2iZ9xSHwKwZILWy6W1C//naOUVafT2iEFUtn+uwf2JC98zfeqDWHEKEplUt35MksqbiDpcb9erWHFE7XaZ1o7pcSr7dTwQE9yFWK7Lp7jJAyELqCYvXWzJtoV8F5WFLZpuRzhxqb2ps8/jkdGlbyqo4B1y29M7W251yQMnKMxgFu6YFH1tHKWXxInnifo6okgp9F7SnQ71IJohDwnRIhB9TIjZTB7xG+mZG9xo5viokiX82+h3BtT87LzcVtvZ5WuVtSZ13/X1re2FiHwfnwngzWaWKG1wI0JdFpbIDvJLMhPzUMSc5BWe1So4JAlcb2X8oLIfB5D0NdYZv8rJj43b24ulg59GrKk6CONzlEZf4d/xxiXnuFvuhzjOd8NNV3Zf9y5JRhIrVgAxwZR2WUPec5lQTzK+MvHD0zQyFLpm36gCjvpwa8GXMlVbKEAEDxr5ErjxOxEUmyclDA3zptwc/j/NUMcoM44ybsWMJa8sQV2p/L6lXEBGvkAcYY1At+2eeliMLi1wyRYGOATgmKmdJi4nd4Hw/H4LfWwC3NB4INN0dAu6XKGEKwhMl+K9dqA/duZqU9QYAyolYdakIODK/brebG/8QHVjUN1UWvhg0kMhrFgn14XInIWTHHQZDFEstrDu8MnHgaaMP1u5rfT02VssXTE/3c+BQSu5Kds9o72dHCfJ2VHBoRkuiHg9gggshg+E+K64M
  template:
    metadata:
      name: adapter-internal-token
      namespace: opencode-system
    type: Opaque
