apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager                    # must match the Config below
  namespace: kube-system                # helm-controller lives here
spec:
  repo: https://charts.jetstack.io
  chart: cert-manager
  version: v1.20.2
  targetNamespace: cert-manager
  set:
    installCRDs: "true"                 # install CRDs with the release
---

apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  valuesContent: |-
    dns01RecursiveNameservers: 10.0.0.1:53
    dns01RecursiveNameserversOnly: true
---

apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
