apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.37.0/controller.yaml
  - cert-manager.yaml
  - metallb
  - agent-sandbox
  - zfs-localpv.yaml
  - kube-prometheus-stack.yaml

patches:
  - path: sealed-secrets-renewal.patch.yaml
