apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lific-data
  namespace: lific
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: openebs-zfspv