apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telegram-collector-state-zfs
  namespace: knowledge
spec:
  storageClassName: openebs-zfspv-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
