apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: anvil

resources:
  - github.com/blogle/anvil//k8s/base?ref=5ed4cd60a52bc6ed124f793b15fea85d73c17cb6
  - certificate.yaml
  - ingress.yaml

images:
  - name: ghcr.io/blogle/anvil
    newTag: sha-5ed4cd60a52bc6ed124f793b15fea85d73c17cb6
  - name: ghcr.io/blogle/anvil-sandbox
    newTag: sha-5ed4cd60a52bc6ed124f793b15fea85d73c17cb6

patches:
  - path: runtime-config.patch.yaml
  - path: profile-pvc.patch.yaml
  - path: profile-deployment.patch.yaml
